### PR TITLE
I think stabby lambdas for multi-line blocks are okay. Don't you?

### PR DESCRIPTION
**Pull request by BrandonMathis**
## What Changes
* Disable Lambda linting

## Why
I prefer

```ruby
scope :name, -> {
  where("this")
    .where("this also")
}
```

over

```ruby
scope :name, (lambda do
  where("this")
    .where("this also")
end)
```

bc of the way that scoping working in ruby, you *have* to surround multi-line lambdas passed as args to functions in parens :(

### CODE REVIEW

**Comment by Ru-T** [comment]
:shipit: :laughing:

**Comment by zachary-kuhn** [comment]
I like this change.

**Comment by zachary-kuhn** [comment]
wait, can't you just use a `do...end` block in these cases? This will show my ignorance.

**Comment by dkniffin** [comment]
:+1:

@zachary-kuhn nope. This is one of the cases where a lambda is needed. Don't ask me why.

**Comment by BrandonMathis** [comment]
@zachary-kuhn the `do ... end` would be passed to `scope` in the example above. That is not what we want. We want the `do ... end` to be passed to `lambda` or `->` hence the parens.

**Pull request merged**
